config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => 'user/registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  resources :user_stocks, only: [:create, :destroy]
  resources :users, only: [:show]
  resources :friendships

  get 'home', to: 'welcome#index'

  get 'my_portfolio', to: 'users#my_portfolio'
  get 'my_friends', to: 'users#my_friends'
  get 'search_friends', to: 'users#search'
  post 'add_friend', to: 'users#add_friend'

  get 'search_stocks', to: 'stocks#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, :class_name => 'User'
end

app/models/stock.rb
class Stock < ApplicationRecord
  has_many :user_stocks
  has_many :users, through: :user_stocks
  def self.new_from_lookup(ticker_symbol)
    begin
      looked_up_stock = StockQuote::Stock.quote(ticker_symbol)
      new(name: looked_up_stock.company_name, ticker: looked_up_stock.symbol, last_price: looked_up_stock.latest_price)
    rescue Exception => e
      return nil
    end
  end

  def self.strip_commas(number)
    number.n.gsub(',', '')
  end

  def self.find_by_ticker(ticker_symbol)
    where(ticker: ticker_symbol).first
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :user_stocks
  has_many :stocks, through: :user_stocks
  has_many :friendships
  has_many :friends, through: :friendships

  def stock_already_added?(ticker_symbol)
    stock = Stock.find_by_ticker(ticker_symbol)
    return false unless stock

    user_stocks.where(stock_id: stock.id).exists?
  end

  def under_stock_limit?
    (user_stocks.count < 10)
  end

  def can_add_stock?(ticker_symbol)
    under_stock_limit? && !stock_already_added?(ticker_symbol)
  end

  def full_name
    return "#{first_name} #{last_name}".strip if first_name || last_name

    'Anonymous'
  end

  def self.search(param)
    param.strip!
    param.downcase!
    to_send_back = (first_name_matches(param) + last_name_matches(param) + email_matches(param)).uniq
    return nil unless to_send_back

    to_send_back
  end

  def self.first_name_matches(param)
    matches('first_name', param)
  end

  def self.last_name_matches(param)
    matches('last_name', param)
  end

  def self.email_matches(param)
    matches('email', param)
  end

  def self.matches(field_name, param)
    User.where("#{field_name} like ?", "%#{param}%")
  end

  def except_current_user(users)
    users.reject { |user| user.id == id }
  end

  def not_friends_with?(friend_id)
    friendships.where(friend_id: friend_id).count < 1
  end
end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def destroy
    @friendship = current_user.friendships.where(friend_id: params[:id]).first
    @friendship.destroy
    flash[:notice] = 'Friend was successfully removed'
    redirect_to my_friends_path
  end
end

app/controllers/stocks_controller.rb
# ArticlesController
class StocksController < ApplicationController
  def search
    if params[:stock].blank?
      flash.now[:danger] = 'Please enter a symbol to search'
    else
      @stock = Stock.new_from_lookup(params[:stock])
      flash.now[:danger] = 'Could not find symbol' unless @stock
    end
    respond_to do |format|
      format.js { render partial: 'users/result' }
    end
  end
end

app/controllers/user/registrations_controller.rb
class User::RegistrationsController < Devise::RegistrationsController
  before_action :configure_premitted_parameters

  protected

  def configure_premitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController
  def create
    stock = Stock.find_by_ticker(params[:stock_ticker])
    if stock.blank?
      stock = Stock.new_from_lookup(params[:stock_ticker])
      stock.save
    end
    @user_stock = UserStock.create(user: current_user, stock: stock)
    flash[:success] = "Stock #{@user_stock.stock.name} was successfully added to your portfolio"
    redirect_to my_portfolio_path
  end

  def destroy
    stock = Stock.find(params[:id])
    @user_stock = UserStock.where(user_id: current_user, stock_id: stock.id).first
    @user_stock.destroy
    flash[:notice] = 'Stock was successfully removed from portfolio'
    redirect_to my_portfolio_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def my_portfolio
    @user = current_user
    @user_stocks = current_user.stocks
  end

  def my_friends
    @friendships = current_user.friends
  end

  def search
    if params[:search_param].blank?
      flash.now[:danger] = 'Please enter a name or email address'
    else
      @users = User.search(params[:search_param])
      @users = current_user.except_current_user(@users)
      flash.now[:danger] = 'Could not find users' if @users.blank?
    end
    respond_to do |format|
      format.js { render partial: 'friends/result' }
    end
  end

  def add_friend
    @friend = User.find(params[:friend])
    current_user.friendships.build(friend_id: @friend.id)

    if current_user.save
      flash[:success] = 'Friend was successfuly added'
    else
      flash[:danger] = 'Friend was failed to added'
    end
    redirect_to my_friends_path
  end

  def show
    @user = User.find(params[:id])
    @user_stocks = @user.stocks
  end
end

app/controllers/welcome_controller.rb
# ArticlesController
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

app/views/friends/_lookup.html.erb
<h1>My Friends</h1>
<h3>Search for friends</h3>
<div id="friend_lookup">
  <%= form_tag search_friends_path, remote:true, method: :get, id: "friends-lookup-form" do %>
    <div class="form-group row no-padding text-center col-md-12">
      <div class="col-md-10">
        <%= text_field_tag :search_param, 
            params[:search_param], 
            placeholder: "Search for Friends",
            autofocus: true,
            class: "form-control search-box input-lg"
        %>
      </div>
      <div class="col-md-2">
        <%= button_tag(type: :submit, class: "btn btn-lg btn-success") do %>
          <i class="fa fa-search"></i> Search for a friends
        <% end %>
      </div>
    </div>
  <% end %>
</div>
<div id="results">
  <%= render 'result'%>
</div>

app/views/friends/_result.html.erb
<% if params[:action] == "search"%>
  <div class="results-block">
    <%= bootstrap_flash %>
  </div>
<% end %>
<% if @users && @users.size >0 %>
  <div id="friend-lookup-results" class="well results-block col-md-10">
    <table class="search-results-table col-md-12">
      <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><strong>Name:</strong><%= user.full_name%></td>
          <td><strong>Email:</strong><%= user.email%></td>
          <td>
            <strong>Profile: </strong>
            <%= link_to "View", user_path(user), 
                class: "btn btn-xs btn-success"%>
            <% if current_user.not_friends_with?(user.id) %>
              <%= link_to "Add as friend", add_friend_path(user: current_user, friend: user), 
                  class: "btn btn-xs btn-primary", method: :post %>
            <% else %>
              <span class="label label-primary">You are already friends</span>
            <% end %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
<% end %>

app/views/friends/_result.js.erb
$('#results').html("<%= j (render 'friends/result.html') %>")

app/views/layouts/_navigation.html.erb
<div class="navbar navbar-default navbar-static-top">
  <div class="container">
  <%= link_to 'Finance Tracker', root_path, class: "navbar-brand"%>
  <% if current_user %>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="navbar-collapse collapse navbar-responsive-collapse">
        <ul class="nav navbar-nav col-md-6">
          <li><%= link_to "My portfolio", my_portfolio_path  %></li>
          <li><%= link_to "My Profile", edit_registration_path(current_user) %></li>
          <li><%= link_to "My Friends", my_friends_path  %></li>
        </ul>
        <ul class="nav navbar-right col-md-4">
          <li class="col-md-8 user-name text-right">
            <i class="fa fa-user"></i>
            <%= current_user.full_name.present? ? current_user.full_name : current_user.email%>
          </li>
          <li class="col-md-4 logout"> <%= link_to("logout", destroy_user_session_path, 
              class: "btn btn-xs btn-danger", method: :delete) %> </li>
        </ul>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "FinanceTracker" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <%= render 'layouts/navigation' %>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2018</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/stocks/_list.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Symbol</th>
      <th>Current Price</th>
      <% if @user.id == current_user.id %>
        <th>Actions</th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @user_stocks.each do |user_stock| %>
      <tr>
        <td><%= user_stock.name %></td>
        <td><%= user_stock.ticker %></td>
        <td><%= user_stock.last_price %></td>
        <% if @user.id == current_user.id %>
          <td><%= link_to "Delete this stock", user_stock_path(user_stock), method: :delete,
                  data: { confirm: "Are you sure?" }, class: "btn btn-xs btn-danger" %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_result.html.erb
<% if params[:action] == "search"%>
  <div class="results-block">
    <%= bootstrap_flash %>
  </div>
<% end %>
<% if @stock%>
  <div class="well results-block">
    <strong>Symbol:</strong> <%= @stock.ticker %>
    <strong>Name:</strong> <%= @stock.name %>
    <strong>Last Price:</strong> <%= @stock.last_price %>
    <% if current_user.can_add_stock?(@stock.ticker) %>
      <%= link_to "Add to my stocks", user_stocks_path(user: current_user, stock_ticker: @stock.ticker),
          class: "btn btn-xs btn-success", method: :post
      %>
    <% else %>
      <span class="label label-default">
        Stock cannot be added because you have already added
        <% if !current_user.under_stock_limit? %>
          10 stocks
        <% end %>
        <% if current_user.stock_already_added?(@stock.ticker) %>
          this stock
        <% end %>
      </span>
    <% end %>
  </div>
<% end %>

app/views/users/_result.js.erb
$('#results').html("<%= j (render 'users/result.html') %>")

app/views/users/my_friends.html.erb
<%= render 'friends/lookup'%>

<% if @friendships.size > 0  %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th colspna="3" class="page-header">
          <h2>My friends</h2>
        </th>
      </tr>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @friendships.each do |friend| %>
        <tr>
          <td><%= friend.full_name %></td>
          <td><%= friend.email %></td>
          <td>
            <%= link_to "View Profile", user_path(friend), class: "btn btn-primary btn-xs"%>
            <td><%= link_to "Remove", friendship_path(friend), method: :delete,
                    data: { confirm: "Are you sure?" }, class: "btn btn-xs btn-danger" %></td>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="row col-lg-12">
    <p class="lead">You don't have any friends yet. Please add some!</p>
  </div>
<% end %>

app/views/users/my_portfolio.html.erb
<h1>My portfolio</h1>
<h3>Search for stocks</h3>
<div id="stock_lookup">
  <%= form_tag search_stocks_path, remote:true, method: :get, id: "stock-lookup-form" do %>
    <div class="form-group row no-padding text-center col-md-12">
      <div class="col-md-10">
        <%= text_field_tag :stock, 
            params[:stock], 
            placeholder: "Stock ticker symbol",
            autofocus: true,
            class: "form-control search-box input-lg"
        %>
      </div>
      <div class="col-md-2">
        <%= button_tag(type: :submit, class: "btn btn-lg btn-success") do %>
          <i class="fa fa-search"></i> Lookup a stock
        <% end %>
      </div>
    </div>
  <% end %>
</div>
<div id="results">
  <%= render 'result'%>
</div>
<%= render 'stocks/list'%>

app/views/users/show.html.erb
<h2>User Details</h2>
<dl class="dl-horizontal">
  <dt><strong>Full Name</strong></dt>
  <dd><%= @user.full_name %></dd>
  <dt><strong>Email</strong></dt>
  <dd><%= @user.email %></dd>
</dl>
<% if @user.stocks.size > 0%>
  <%= render 'stocks/list'%>
<% else %>
  <p class="lead">This User is not tracking any stocks</p>
<% end %>

<%= link_to 'Back', my_friends_path, class: "btn btn-primary"%>

app/views/welcome/index.html.erb
<h1>This is the welcome page for Aidan's finance tracker website</h1>